"""AI News Credibility Lab — Paste a headline or short article snippet and get an interactive, educational analysis of whether it looks AI-generated, why, and how to verify or improve its trustworthiness."""

from ..base import (call_openrouter, call_pollinations, extract_json, fetch_image,
    query_db, load_json_data, web_search, fetch_url, wikipedia_summary, fetch_rss,
    generate_qr, generate_wordcloud, tmp_sqlite, call_huggingface, call_gTTS,
    classify_text, embed_text, text_to_speech, CDN_LIBS, PUBLIC_APIS)
import json as _json

ACTIONS = {
    "start": {
        "prompt": "You are an expert media-literacy educator and AI analyst. A user will provide {topic} (a short news headline or article snippet). Analyze it and teach the user about signs of AI-generated news and practical verification steps. Return only a single JSON object with the exact fields below. Do not include extra commentary outside the JSON. Fields:\n\n- input: echo the original {topic} string\n- summary: one-sentence neutral summary of the claim/content\n- likelihood_score: integer 0-100 assessing how likely this text was generated by a large language model or automated generator\n- likelihood_reason: one-sentence justification for the score\n- signals: array of objects [{\"signal\":\"short name\",\"explanation\":\"why this signal appears in the text\"}] listing up to 6 detected signals that support the likelihood assessment\n- verifiability_checks: array of up to 6 concrete, ordered checks the user can perform (search queries, metadata checks, image forensics, source tracing)\n- suggested_edits_for_trust: array of up to 5 short edits or additions that would make the item more credible (e.g., add named sources, timestamps, quotes with attribution)\n- mini_lesson: a short paragraph (2-4 sentences) explaining one core reason AI-generated news can be less trusted and one practical habit to adopt\n- confidence: integer 0-100 expressing your confidence in this analysis\n- teaching_questions: array of 2-3 short reflective questions the user can ask themselves when evaluating news\n- related_resources: array of up to 3 objects {\"title\":\"resource title\",\"note\":\"one-line why useful\"}\n\nBe concise in each field. Output only valid JSON.",
        "parse": "json"
    },
    "explore": {
        "prompt": "Now dig deeper on this user input: {user_input}. Return only a JSON object with these fields. Do not include extra text.\n\n- input: echo {user_input}\n- deeper_analysis: 4-6 short bullet sentences expanding on factual gaps, logical leaps, or stylistic patterns that suggest automation or human bias\n- framing_and_bias_flags: array of flagged framing devices or biases (e.g., sensationalist language, omission of counterclaims, partisan framing) with one-line explanations\n- counter_evidence_search_queries: array of 6 ready-to-run search queries (search engine friendly) that would help verify or falsify the claims\n- probable_generation_method: short label (e.g., \"neural LM (GPT-like)\", \"templated feed-generated\") plus one-line rationale\n- detection_methods_explained: array of 3 objects {\"method\":\"name\",\"how_it_works\":\"one-line explanation of how to use or what it reveals\"}\n- teachable_example_rewrite: object {\"rewrite\":\"a concise rewritten version of the input that increases transparency and verifiability\",\"changes_explained\":[\"one-line explanation per change\"]}\n- next_steps_for_user: array of 4 practical steps the user can take now (mix of manual checks and tools to run)\n- estimated_time_minutes: integer estimate of how long the next-steps list will take in total\n\nKeep outputs practical and educational, aimed at a curious non-expert. Output only valid JSON.",
        "parse": "json"
    }
}

def handle(action: str, data: dict) -> dict:
    """Handle project actions."""
    if action == 'info':
        return {"name": META["name"], "description": META["description"], "actions": list(ACTIONS.keys())}
    
    action_config = ACTIONS.get(action)
    if not action_config:
        return {"error": f"Unknown action: {action}. Available: {list(ACTIONS.keys())}"}
    
    # Build prompt with user data
    prompt = action_config["prompt"]
    for key, value in data.items():
        prompt = prompt.replace("{" + key + "}", str(value))
    
    # Inject database data if action has a db_query
    db_query = action_config.get("db_query")
    if db_query:
        db_rows = query_db(db_query)
        # Replace {db_*} placeholders with JSON data
        for placeholder in ["db_models", "db_timeline", "db_glossary", "db_gpus", "db_datasets", "db_languages"]:
            if "{" + placeholder + "}" in prompt:
                prompt = prompt.replace("{" + placeholder + "}", _json.dumps(db_rows, default=str)[:3000])
    
    # Call AI
    raw = call_openrouter(prompt)
    
    # Parse response
    if action_config.get("parse") == "json":
        parsed = extract_json(raw)
        if parsed:
            return {"result": parsed, "date": META.get("date", "")}
        return {"result": {"text": raw}, "date": META.get("date", ""), "parse_note": "returned as text"}
    
    return {"result": {"text": raw}, "date": META.get("date", "")}

META = {
    "name": "AI News Credibility Lab",
    "description": "Paste a headline or short article snippet and get an interactive, educational analysis of whether it looks AI-generated, why, and how to verify or improve its trustworthiness.",
    "category": "AI Education",
    "date": "2026-02-23"
}
